import { start } from './js/start-func';
import './js/modal-log-in';
import './js/log-in';
import './js/pagination';
import './js/watchedLib';
import './js/modal_film';
import './js/themeSwitcher';
import './js/spinner';
import './js/scroll';
import './js/footer-modal';
start();
